### ISSUE TITLE
Intermittent issue where authentication tab shows invalid state  

### ISSUE THREAD

**Issue by DHaussermann** [mattermost-community/mattermost-plugin-msteams-meetings#25]
There seems to be an intermittent issue where the tab used to authenticate to Azure shows `invalid state`. 

This did not occur on each attempt. Interestingly. The user connected without issue and there seem to be no functional problems. 

I saw no indication in the logs as to why the browser said `invalid state` and the authentication seemed to work fine.

Steps used:
- Login to Mattermost
- Type /msteams start 
- Click the connection link (opens in a new tab)
- Provide credetials

**Observed**: Invalid State
**Expected**: Message that authentication succeeded and I should close the tab.

![MS-TeamsInavlidUser](https://user-images.githubusercontent.com/35588783/97136123-a6d46480-1728-11eb-8881-6d7d5c4e8da4.PNG)

**Comment by DHaussermann** [comment]
@larkox do you have any suggestions as to a possible cause for this issue as it seems to be intermittent.

**Comment by larkox** [comment]
It is weird that it is intermitent, but I think where I have to look. Will try to fix.

**Comment by DHaussermann** [comment]
@larkox  I can reproduce this issue today. 
![Screen Shot 2020-11-12 at 10 58 00 AM](https://user-images.githubusercontent.com/35588783/98966993-edbcab00-24d9-11eb-8ed6-4a04df7e298f.png)

Strangely, it seems that the auth works as a meeting was created for the affected user. Logs showed no record for MS teams after the message that user had to connect an account. 
![Screen Shot 2020-11-12 at 10 59 56 AM](https://user-images.githubusercontent.com/35588783/98967015-f3b28c00-24d9-11eb-9224-0aadcaf2e5e5.png)
  
Steps:
- Deployed build `f00ca1ce`
- Get team invite link
- Open new incognito session
- Create a new user and login
- Type /mstmeetings  start
- Click on the connection link
- In new tab - login as test user (Sent DM)
**Expected**: Message that authentication worked and tab should be closed
**Observed** Invalid state message

**Comment by AayushChaudhary0001** [comment]
@wiggin77 I tried to reproduce the issue but was not able to do so.
Observed behaviour: When I clicked the connection link and entered the credentials, I did not see any invalid state message.

**Comment by raghavaggarwal2308** [comment]
Closing for now, can reopen if anyone faces this issue again
