### ISSUE TITLE
Add command autocomplete

### ISSUE THREAD

**Issue by mickmister** [mattermost-community/mattermost-plugin-msteams-meetings#53]

**Comment by jeromegrosse** [comment]
I can do it!

**Comment by mickmister** [comment]
Great! It's all yours @jeromegrosse :tada:

**Comment by jeromegrosse** [comment]
I'm currently having some issues building this plugin because it lacks ARM64 support. Are there any plan to support it? Maybe I could tackle that first?

**Comment by jeromegrosse** [comment]
Alright, I've finally used an AMD64 for the PR.
