### ISSUE TITLE
in the desktop app msteem call UI is not same as Web-app UI.

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost-community/mattermost-plugin-msteams-meetings#68]
in the desktop app after run the /msteem start command i'm getting UI like this 
![image](https://user-images.githubusercontent.com/89907719/160234609-807a8b35-232a-47b2-a0db-600307d0ab7e.png)

and i'm Expecting the UI like this 
![image](https://user-images.githubusercontent.com/89907719/160234632-5ef26538-8b4f-4bd5-8757-4c3fbac58de6.png)

i'm using the same server for Web & Desktop app and i'm Using The Master build.

**Comment by dipak-demansol** [comment]
some times the same issue also generate in the web-app, after installing the master build but after few minutes some how the UI change and its looks proper. but in desktop app its not changing.

**Comment by larkox** [comment]
Seems like for some reason the plugin is crushing, not sure exactly where.

If the plugin is not running properly, the posts are rendered as normal posts (therefore, the `meeting started at this link` post), but if the plugin is running, it will use the custom render specified by the plugin.

I wonder why the plugin crash only in desktop.

**Comment by mickmister** [comment]
MM thread on community for more context https://community-daily.mattermost.com/core/pl/dsme8d4mc7ffi8iutktjo9k4pr

**Comment by raghavaggarwal2308** [comment]
@dipak-demansol Are you still facing the issue or we can close it?

**Comment by raghavaggarwal2308** [comment]
Closing for now, can reopen if someone else faces this issue.
