### ISSUE TITLE
Add subject to meetings

### ISSUE THREAD

**Issue by larkox** [mattermost-community/mattermost-plugin-msteams-meetings#8]
Meetings can have a subject. How do we want to provide the subject?

Shall we use the same behaviour as Jitsi?

**Comment by Kshitij-Katiyar** [comment]
Hi @larkox @wiggin77,
I explored a bit on multiple video meeting plugins, my suggestion is to use a command similar to 
` /mstmeetings start MEETING_TOPIC`.

Keeping the behavior similar to `Jitsi` can be complex for the users, we can use the last option provided by Jitsi plugin.
![image](https://github.com/user-attachments/assets/634f12ad-8e8d-4efb-9b82-0bdb3d1b59b9)
@AayushChaudhary0001 What are your opinions on this approach?

**Comment by AayushChaudhary0001** [comment]
@Kshitij-Katiyar Yes we should implement this, it maintains consistency across all the plugins and provides a meaningful approach to solve this issue.
